#!/bin/sh
fswatch -0 -o /Users/piperck/Desktop/gogogo/x  | xargs -0 -n 1 -I {} rsync -avz --progress --exclude .git /Users/piperck/Desktop/gogogo/x piperck@120.27.206.130:/home/piperck/project
#rsync -avz --progress --exclude .git /Users/piperck/Desktop/gogogo/x piperck@120.27.206.130:/home/piperck/project
